# version
KUBE_VERSION: 1.15.0
KUBERNETES_VERSION: "v{{ KUBE_VERSION }}"

# image repository
KUBE_IMAGE_REPO: registry.aliyuncs.com/google_containers

# master
KUBE_MASTER_API_ADDR: 192.168.1.21
KUBE_TAINT_MASTER: true

# calico
KUBE_CALICO_VERSION: 3.7
KUBE_CALICO_URL: https://docs.projectcalico.org/v3.7/manifests/calico.yaml
KUBE_POD_CIDR: 10.241.0.0/16
KUBE_CALICO_REACH_HOST: 192.168.1.1

# cri
# docker | contrainerd
KUBE_CRI: docker
