- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: kube-cluster/prepareOS }

- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: kube-cluster/docker }
  tags:
    - docker

- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: kube-cluster/packages }
  tags:
    - packages

- hosts: masters
  gather_facts: no
  vars:
    node_role: master
  roles:
    - { role: kube-cluster/images }
  tags:
    - images

- hosts: workers
  gather_facts: no
  vars:
    node_role: worker
  roles:
    - { role: kube-cluster/images }
  tags:
    - images

- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: kube-cluster/init }
    - { role: kube-cluster/adminUser }

- hosts: masters[0]
  gather_facts: no
  become: yes
  become_user: "{{ KUBE_ADMIN_USER }}"
  roles:
    - { role: kube-cluster/calico }
  tags:
    - network

- hosts: workers
  gather_facts: no
  roles:
    - { role: kube-cluster/join }
