- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: prepare }

# install container runtime - docker or containerd
- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: cri }
  tags:
    - cri

# pull k8s images
- hosts: masters
  gather_facts: no
  roles:
    - { role: images/master }
  tags:
    - images

- hosts: workers
  gather_facts: no
  roles:
    - { role: images/worker }
  tags:
    - images

# init control-plane node
- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: init }

# install pod network add-on - calico
- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: calico }
  tags:
    - network

# join nodes
- hosts: workers
  gather_facts: no
  roles:
    - { role: join }
