- hosts: masters[0]
  gather_facts: no
  tasks:
    - name: create kube init work directory
      file:
        path: "{{ KUBE_INIT_DIR }}"
        state: directory

- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: prepare }

# install container runtime - docker or containerd
- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: cri }
  tags:
    - cri

# init control-plane node
- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: init }
  tags:
    - init

# install pod network add-on - calico
- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: calico }
  tags:
    - network

# join nodes
- hosts: workers
  gather_facts: no
  roles:
    - { role: join }
  tags:
    - join
