- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: prepareOS }

- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: cri }
  tags:
    - cri

- hosts: masters:workers
  gather_facts: no
  roles:
    - { role: packages }
  tags:
    - packages

- hosts: masters
  gather_facts: no
  roles:
    - { role: images/master }
  tags:
    - images

- hosts: workers
  gather_facts: no
  roles:
    - { role: images/worker }
  tags:
    - images

- hosts: masters[0]
  gather_facts: no
  roles:
    - { role: init }
    - { role: adminUser }

- hosts: masters[0]
  gather_facts: no
  become: yes
  become_user: "{{ KUBE_ADMIN_USER }}"
  roles:
    - { role: calico }
  tags:
    - network

- hosts: workers
  gather_facts: no
  roles:
    - { role: join }
