- name: install kubectl
  yum:
    name: "kubectl-{{ KUBE_VERSION }}"
    state: present
    allow_downgrade: yes

- name: create kube-cluster admin user (kube-admin-user 1/4)
  user:
    name: "{{ KUBE_ADMIN_USER }}"
    password: "{{ lookup('password', 'kube_admin_password.octv length=15 encrypt=sha512_crypt') }}"
    comment: kubernetes cluster manager
    state: present

- name: set authorized key (kube-admin-user 2/4)
  authorized_key:
    user: "{{ KUBE_ADMIN_USER }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: create .kube directory (kube-admin-user 3/4)
  become: yes
  become_user: "{{ KUBE_ADMIN_USER }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0700

- name: copy admin.conf to user's kube config (kube-admin-user 4/4)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ KUBE_ADMIN_USER }}/.kube/config"
    remote_src: yes
    owner: "{{ KUBE_ADMIN_USER }}"

