- name: get join command
  delegate_to: master1
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: False

- name: join cluster
  shell: "{{ join_command.stdout_lines[0] }} --ignore-preflight-errors all >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
