- name: pull k8s images on workers (1/3) | get image version
  shell: "kubeadm config images list | grep -e 'coredns' -e 'kube-proxy'"
  register: k8s_images_list_worker
  changed_when: False
  run_once: true

- name: pull k8s images on workers (2/3) | change images repo
  delegate_to: 127.0.0.1
  shell: "echo -e '{{ k8s_images_list_worker.stdout }}' | sed -e 's#k8s.gcr.io/coredns#coredns/coredns#g' -e 's/k8s.gcr.io/mirrorgooglecontainers/g'"
  register: k8s_images_list_repo_worker
  changed_when: False
  run_once: true

- name: pull k8s images on workers (3/3) | pull images
  docker_image:
    name: "{{ item.0 }}"
    repository: "{{ item.1 }}"
    state: present
  loop: "{{ k8s_images_list_repo_worker.stdout_lines | zip(k8s_images_list_worker.stdout_lines) | list }}"
 
