- name: download CentOS-Base repo (aliyun mirrors)
  get_url: 
    url: http://mirrors.aliyun.com/repo/Centos-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    force: yes
    backup: yes
  register: base_repo

- name: upgrade all packages first time
  yum:
    name: '*'
    state: latest
    update_cache: true
  when: base_repo.changed
