- name: get images list
  shell: "kubeadm config images list --image-repository {{ KUBE_IMAGE_REPO }} 2>/dev/null
    | sed -e 's#{{ KUBE_IMAGE_REPO }}/coredns#docker.io/coredns/coredns#g'"
  register: master_images
  changed_when: False
  run_once: true

- name: pull images
  docker_image:
    name: "{{ item }}"
    source: pull
    state: present
  loop: "{{ master_images.stdout_lines | list }}"
  when: KUBE_CRI == "docker"

- name: pull images
  shell: "ctr images pull {{ item }}"
  loop: "{{ master_images.stdout_lines | list }}"
  when: KUBE_CRI == "containerd"
