- name: add docker-ce repo (aliyun mirrors)
  get_url: 
    url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install device-mapper-persistent-data, lvm2
  yum:
    name:
      - device-mapper-persistent-data
      - lvm2
    update_cache: true
    state: present

- name: install containerd
  yum:
    name: containerd.io
    state: present

- name: check containerd if configured
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config_file

- name: configure containerd
  block:
    - name: create config directory
      file:
        path: /etc/containerd
        state: directory
    
    - name: create config file
      shell: containerd config default > /etc/containerd/config.toml
  when: not containerd_config_file.exists
    
- name: use systemd cgroup driver
  replace:
    path: /etc/containerd/config.toml
    regexp: 'systemd_cgroup = false'
    replace: 'systemd_cgroup = true'

- name: start containerd
  systemd:
    name: containerd
    enabled: yes
    daemon_reload: yes
    state: started
