- name: Prerequisites
  block:
    - modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
    - sysctl:
        name: "{{ item }}"
        value: 1
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables

- name: install containerd
  block:
    - get_url: 
        url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - yum:
        name:
          - device-mapper-persistent-data
          - lvm2
        update_cache: true
        state: present

    - yum:
        name: containerd.io
        state: present

- name: configure containerd
  block:
    - file:
        path: /etc/containerd
        state: directory
    
    - shell: containerd config default > config.toml
      args:
        chdir: /etc/containerd/
        creates: config.toml
    
    - replace:
        path: /etc/containerd/config.toml
        regexp: 'systemd_cgroup = false'
        replace: 'systemd_cgroup = true'

- name: start containerd
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: started
