- name: install docker
  block:
    - get_url: 
        url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    
    - yum:
        name:
          - device-mapper-persistent-data
          - lvm2
        update_cache: true
        state: present
    
    - yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    
    - copy:
        src: daemon.json
        dest: /etc/docker/
    
    - systemd:
        name: docker
        enabled: yes
        daemon_reload: yes
        state: started
