- name: docker cri
  import_tasks: docker.yml
  when: KUBE_CRI == "docker"

- name: containerd cri
  import_tasks: containerd.yml
  when: KUBE_CRI == "containerd"

- name: cri-o
  import_tasks: cri-o.yml
  when: KUBE_CRI == "cri-o"
