- name: download calico network manifest
  get_url:
    url: "{{ KUBE_CALICO_URL }}"
    dest: "{{ KUBE_INIT_DIR }}/calico-{{ KUBE_CALICO_VERSION }}.yml"

- name: change pod cidr
  replace:
    path: "{{ KUBE_INIT_DIR }}/calico-{{ KUBE_CALICO_VERSION }}.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '192\.168\.0\.0/16', replace: '{{ KUBE_POD_CIDR }}' }
    - { regexp: '"log_level": "info"', replace: '"log_level:" "warning"' }
    - { regexp: 'value: "info"', replace: 'value: "warning"' }

- name: change ip detect method
  blockinfile:
    path: "{{ KUBE_INIT_DIR }}/calico-{{ KUBE_CALICO_VERSION }}.yml"
    insertafter: "autodetect"
    block: |2
                  # set auto-detect method
                  - name: IP_AUTODETECTION_METHOD
                    value: "can-reach=192.168.1.1"

- name: install Pod network
  shell: "KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f calico-{{ KUBE_CALICO_VERSION }}.yml
    >> calico.txt"
  args:
    chdir: "{{ KUBE_INIT_DIR }}"
    creates: calico.txt
