- name: pull k8s images on masters (1/3) | get images list
  shell: "kubeadm config images list"
  register: k8s_images_list
  changed_when: False
  run_once: true

- name: pull k8s images on masters (2/3) | change images repo
  delegate_to: 127.0.0.1
  shell: "echo -e '{{ k8s_images_list.stdout }}' | sed -e 's#k8s.gcr.io/coredns#coredns/coredns#g' | sed -e 's/k8s.gcr.io/mirrorgooglecontainers/g'"
  register: k8s_images_list_repo
  changed_when: False
  run_once: true
 
- name: pull k8s images on masters (3/3) | pull images and tag
  docker_image:
    name: "{{ item.0 }}"
    repository: "{{ item.1 }}"
    state: present
  loop: "{{ k8s_images_list_repo.stdout_lines | zip(k8s_images_list.stdout_lines) | list }}"
