- name: firewalld
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    # apiServer
    - 6443/tcp
    # kubelet
    - 10250/tcp
    # calico
    - 179/tcp
    - 4789/udp
