- name: create init work directory
  file:
    path: $HOME/kube-init
    state: directory

- name: initialize the cluster
  shell: "kubeadm init --kubernetes-version={{ KUBERNETES_VERSION }} --apiserver-advertise-address={{ KUBE_MASTER_API_ADDR }} --pod-network-cidr={{ KUBE_POD_CIDR }} >> cluster_initialized.txt"
  args:
    chdir: $HOME/kube-init
    creates: cluster_initialized.txt

- name: enable schedule pods on master
  become: yes
  become_user: "{{ KUBE_ADMIN_USER }}"
  shell: kubectl taint nodes --all node-role.kubernetes.io/master- >> taint_master.txt
  args:
    chdir: $HOME/kube-calico
    creates: taint_master.txt
  when: TAINT_MASTER
